import Head from "next/head";
import { NextLink } from "@mantine/next";
import prisma from "../../lib/prisma";
import {
  
  Table,
  Group,
  Text,
  ActionIcon,
  
  ScrollArea,
  Menu,
  Grid,
  ThemeIcon,
} from "@mantine/core";
import {
  IconPencil,
  IconTrash,
  IconEdit,
  IconNote,
  IconReportAnalytics,
  IconUser,
  IconDots,
} from "@tabler/icons";

const jobColors = {
  engineer: "green",
  manager: "cyan",
  designer: "pink",
};


export default function Vacunados({ personas }) {
  // console.log(personas )
  const rows = personas.map((persona) => (
    <tr key={persona.doc_identidad}>
      <td>
        <Group spacing="sm">
          <ThemeIcon variant="light" radius="lg" size="lg">
            <IconUser />
          </ThemeIcon>
          {persona.nombre_per}
        </Group>
      </td>
      <td>
        <Group spacing="sm">
          <Text size="sm" color="dimmed">
            {persona.apellido_per}
          </Text>
        </Group>
      </td>

      <td>
      <Group spacing="sm">
        <Text size="sm" color="dimmed">
          {persona.doc_identidad}
        </Text>

        </Group>
      </td>
      <td>
      <Group spacing="sm">
        <Text size="sm" color="dimmed">
          {persona.sexo}
        </Text>

        </Group>
      </td>

      <td>
      <Group spacing="sm">
        <Text size="sm" color="dimmed">
          {persona.fecha_nac}
        </Text>

        </Group>
      </td>
      <td>
      <Group spacing="sm">
        <Text size="sm" color="dimmed">
          {persona.n_telefono_per}
        </Text>

        </Group>
      </td>

      <td>
      <Group spacing="sm">
        <Text size="sm" color="dimmed">
          {persona.reside.cod_municipio}
        </Text>

        </Group>
      </td>
      <td>
        <Group spacing={0} position="center">

          <Menu transition="pop" withArrow position="right-end">
            <Menu.Target>
              <ActionIcon>
                <IconDots size={16} stroke={1.5} />
              </ActionIcon>
            </Menu.Target>
            <Menu.Dropdown>
             

              <Menu.Item
                icon={<IconNote size={16} stroke={1.5} />}
                component={NextLink}
                href={`/vacunados/${persona.doc_identidad}`}
              >
                Mas Informacion
              </Menu.Item>
              <Menu.Item icon={<IconEdit size={16} stroke={1.5} />}>
                Editar Informacion
              </Menu.Item>
              <Menu.Item
                icon={<IconTrash size={16} stroke={1.5} />}
                color="red"
              >
                Eliminar
              </Menu.Item>
            </Menu.Dropdown>
          </Menu>
        </Group>
      </td>
    </tr>
  ));

  return (
    <div>
      <Head>
        <title>Vacunados</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/heal.ico" />
      </Head>
      <Grid justify="center" mt={50}>
        <ScrollArea>
          <Table sx={{ minWidth: 800 }} verticalSpacing="sm" fontSize="md" striped highlightOnHover>
            <thead>
              <tr>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Cedula</th>
                <th>Sexo</th>
                <th>Fecha NA</th>
                <th>Telefono</th>
                <th>Reside</th>
                <th>Detalles</th>
                <th />
              </tr>
            </thead>
            <tbody>{rows}</tbody>
          </Table>
        </ScrollArea>
      </Grid>
    </div>
  );
}

export const getStaticProps = async () => {
  
  const pern = await prisma.persona.findMany(
    {
      include:{
        reside:true,
      }
    }
  );
//  console.dir(pern, { depth: null })
  return {
     props: {
        personas: JSON.parse(JSON.stringify(pern )) 
     },
     
  }
  

}