import Head from "next/head";
import { Card, Image, Text, Divider, Button, Group, Grid } from "@mantine/core";


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/heal.ico" />
      </Head>

      <main>
        <Grid justify="center" mt={100}>
          <Grid.Col md={6} lg={3}>
            <Card shadow="sm" p="lg" radius="md" withBorder>
              <Card.Section>
                <Image
                  src="vacunacion.jpg"
                  height={160}
                  alt="Norway"
                />
              </Card.Section>

              <Group position="apart" mt="md" mb="xs">
                <Text weight={500} size="xl">Registrar Vacunados</Text>

              </Group>
              <Divider size="sm" />
              <Text size="lg" color="dark">
               Registrar persona vacunada , informacion de vacunas.
              </Text>

              <Button
                
                color="blue"
                fullWidth
                mt="md"
                radius="md"
              >
                Registrar
              </Button>
            </Card>
          </Grid.Col>

          <Grid.Col md={6} lg={3}>
            <Card shadow="sm" p="lg" radius="md" withBorder>
              <Card.Section>
                <Image
                  src="tratamiento.jpg  "
                  height={160}
                  alt="Norway"
                />
              </Card.Section>

              <Group position="apart" mt="md" mb="xs">
                <Text weight={500} size="xl">Control de Contagio</Text>
 
              </Group>
              <Divider size="sm" />
              <Text size="lg" color= "dark">
                Administar contagiados y sus tratamientos, informacion de centros de salud.
               
              </Text>

              <Button
                
                color="blue"
                fullWidth
                mt="md"
                radius="md"
              >
                Entrar
              </Button>
            </Card>
          </Grid.Col>

          
        </Grid>
      </main>
    </div>
  );
}
