import Head from "next/head";
import {
  Avatar,
  Badge,
  Table,
  Group,
  Text,
  ActionIcon,
  Anchor,
  ScrollArea,
  Menu,
  Grid,
} from "@mantine/core";
import { IconPencil, IconTrash,
    IconMessages,
    IconNote,
    IconReportAnalytics,
    
    IconDots,} from "@tabler/icons";

const jobColors = {
    engineer: 'blue',
    manager: 'cyan',
    designer: 'pink',
  };

  const elements = [
    {
      avatar: "https://images.unsplash.com/photo-1624298357597-fd92dfbec01d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=250&q=80",
      name: "Robert Wolfkisser",
      job: "Engineer",
      email: "rob_wolf@gmail.com",
      phone: "+44 (452) 886 09 12"
    },
    {
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=250&q=80",
      name: "Bill Horsefighter",
      job: "Designer",
      email: "bhorsefighter@gmail.com",
      phone: "+44 (667) 341 45 22"
    },
    {
      avatar: "https://images.unsplash.com/photo-1630841539293-bd20634c5d72?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=250&q=80",
      name: "Jeremy Footviewer",
      job: "Manager",
      email: "jeremy@foot.dev",
      phone: "+44 (881) 245 65 65"
    }
  ];

export default function Vacunados() {
   

    const rows = elements.map((element) => (
        <tr key={elements.name}>
          <td>
            <Group spacing="sm">
              <Avatar size={30} src={element.avatar} radius={30} />
              <Text size="sm" weight={500}>
                {element.name}
              </Text>
            </Group>
          </td>
    
          <td>
            <Badge
              color={jobColors[element.job.toLowerCase()]}
             
            >
              {element.job}
            </Badge>
          </td>
          <td>
            <Anchor size="sm" href="#" onClick={(event) => event.preventDefault()}>
              {element.email}
            </Anchor>
          </td>
          <td>
            <Text size="sm" color="dimmed">
              {element.phone}
            </Text>
          </td>
          <td>

         
          
        <Group spacing={0} position="right">
          <ActionIcon>
            <IconPencil size={16} stroke={1.5} />
          </ActionIcon>
          <Menu transition="pop" withArrow position="right-end">
            <Menu.Target>
              <ActionIcon>
                <IconDots size={16} stroke={1.5} />
              </ActionIcon>
            </Menu.Target>
            <Menu.Dropdown>
              <Menu.Item icon={<IconMessages size={16} stroke={1.5} />}>Send message</Menu.Item>
              <Menu.Item icon={<IconNote size={16} stroke={1.5} />}>Add note</Menu.Item>
              <Menu.Item icon={<IconReportAnalytics size={16} stroke={1.5} />}>Analytics</Menu.Item>
              <Menu.Item icon={<IconTrash size={16} stroke={1.5} />} color="red">
                Terminate contract
              </Menu.Item>
            </Menu.Dropdown>
          </Menu>
        </Group>
      </td>
        </tr>
      ));

  return (
    <div>
      <Head>
        <title>Vacunados</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/heal.ico" />
      </Head>
      <Grid justify="center" mt={50}>
      <ScrollArea>
      <Table sx={{ minWidth: 800 }} verticalSpacing="sm">
        <thead>
          <tr>
            <th>Employee</th>
            <th>Job title</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Info</th>
            <th />
          </tr>
        </thead>
        <tbody>{rows}</tbody>
      </Table>
    </ScrollArea>
      </Grid>
    </div>
  );
}
